SistemaTeleReabilitacion/urls.py
from django.conf.urls import url

from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/',LoginView.as_view(template_name='login.html'), name="login"),
    path('accounts/profile/',include('apps.inicio.urls', namespace="Inicio")),

    
    path(r'',include('apps.HomePrincipal.urls',namespace='indexHome')),

    path(r'',include('apps.inicio.urls', namespace="inicio")),
    
    path('logout/', LogoutView.as_view(), name="logout"),
    path('paciente/', include('apps.Paciente.urls'), name="Paciente"),
    path('profesional/', include('apps.Profesional.urls'), name="Profesional"),
    path('provincia/', include('apps.Provincia.urls'), name="Provincia")

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/Profesional/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from apps.Profesional.views import ActualizarProfesional,RegistrarProfesional,listarProfesional,actualizarEstado
app_name='Profesional'

urlpatterns=[
  
    path('registrarProfesional/',RegistrarProfesional.as_view(), name="registrarProfesional"),
    path('actualizarProfesional/<int:pk>/',ActualizarProfesional.as_view(), name="actualizarProfesional"),
    path('listarProfesional/',login_required(listarProfesional.as_view()), name="listarProfesional"),  
    path('actualizarestado/',actualizarEstado, name="actualizarestado"),     
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/Profesional/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profesional(models.Model):
    cedula = models.CharField(max_length=20, blank=True, null=True)
    telefono = models.CharField(max_length=15, blank=True, null=True)
    fecha_nacimiento= models.DateField(null=True,blank=True)
    nacionalidad = models.CharField(max_length=50, blank=True, null=True)
    foto = models.ImageField(upload_to='foto/', null=True,blank=True)
    autoidentificacion = models.CharField(max_length=30, blank=True, null=True)
    formacion = models.CharField(max_length=100, blank=True, null=True)
    codigoMSP = models.CharField(max_length=15, blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    
    

apps/Profesional/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.models import User

from django.views.generic import CreateView,ListView,DeleteView,UpdateView,DetailView

from django.contrib import messages
from apps.Profesional.models import Profesional
 

from apps.Profesional.form import Profesionalform
from apps.Paciente.form import Userform

from django.contrib.auth.hashers import make_password
from django.contrib.auth import update_session_auth_hash

from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required

# Create your views here.


class RegistrarProfesional(CreateView):
        model = Profesional
        template_name = "Profesional/RegistrarProfesional.html"
        form_class = Profesionalform
        second_form_class = Userform
        success_url = reverse_lazy('Profesional:listarProfesional')
        def get_context_data(self, **kwargs):
            context= super(RegistrarProfesional,self).get_context_data(**kwargs)
            
            pk = self.request.user.id
            perfil = Profesional.objects.get(user_id=pk)
            if 'form' not in context:
                context['form']= self.form_class(self.request.GET)
            if 'form2' not in context:
                context['form2']= self.second_form_class(self.request.GET)
            context['Profesional']=perfil
            return context
        def post(self, request, *args, **kwargs):
            self.object= self.get_object
            form= self.form_class(request.POST)#empleado
            form2 = self.second_form_class(request.POST)#usuario

            foto=self.request.FILES['foto']
            contrasenia=request.POST['password']
            lacontrasenia=make_password(contrasenia)
            
            foto=self.request.FILES['foto']
            contrasenia=request.POST['password']
            lacontrasenia=make_password(contrasenia)
            
            if form.is_valid() and form2.is_valid():
                investigador = form.save(commit=False)
                investigador.user = form2.save()
                investigador.user.password=make_password(contrasenia)
                investigador.save()
                fs=FileSystemStorage()
                urlFoto=fs.save(foto.name,foto)
                url=fs.url(urlFoto)
                investigador.foto = url
                investigador.save()
                idUser=investigador.user.id
                

                User.objects.filter(pk=idUser).update(
                    password=lacontrasenia
                )

                return HttpResponseRedirect(self.get_success_url())
            else:
                messages.error(request,('Por favor registrese nuevamente'))
                return self.render_to_response(self.get_context_data(form=form, form2=form2))


class ActualizarProfesional(UpdateView):
    model=Profesional
    second_model=User
    template_name = "Profesional/ActualizarProfesional.html"
    form_class =Profesionalform 
    second_form_class = Userform
    success_url = reverse_lazy('Profesional:listarProfesional')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        pku = self.request.user.id
        perfil = Profesional.objects.get(user_id=pku)
        pk = self.kwargs.get('pk',0)
        empleadoid=self.model.objects.get(id=pk)
        user=self.second_model.objects.get(id=empleadoid.user_id)
        if 'form' not in context:
            context['form']= self.form_class()
        if 'form2' not in context:
            context['form2']= self.second_form_class(instance=user)
        context['id']=pk
        context['Profesional']=perfil
        return context
    def post(self, request, *args, **kwargs):
        self.object= self.get_object
        id_empleado=self.kwargs.get('pk',0)
        empleadoid= self.model.objects.get(id=id_empleado)
        user=self.second_model.objects.get(id=empleadoid.user_id)
        idUser=user.id
        form = self.form_class(request.POST, instance=empleadoid)
        form2= self.second_form_class(request.POST, instance=user) 
        
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()

            contrasenia=request.POST['password']
            lacontrasenia=make_password(contrasenia)
            User.objects.filter(pk=idUser).update(
                    password=lacontrasenia
                )
            validar = request.POST['validarFoto']
            if validar == 'SI':
                foto=self.request.FILES['foto']
                if foto.name:
                    fs=FileSystemStorage()
                    urlFoto=fs.save(foto.name,foto)
                    url=fs.url(urlFoto)
                
                    Profesional.objects.filter(pk=empleadoid.id).update(
                        foto=url
                    )

            return HttpResponseRedirect(self.get_success_url())
        else:
            messages.error(request,('Por favor intente nuevamente'))
            return self.render_to_response(self.get_context_data(form=form, form2=form2))



class listarProfesional(ListView):
    model = Profesional
    template_name='Profesional/ListarProfesional.html'
    def get_context_data(self, **kwargs):
        pk = self.request.user.id
        perfil = Profesional.objects.get(user_id=pk)
        context = super().get_context_data(**kwargs)
        context['profesional']=Profesional.objects.exclude(user_id=pk)
        context['Profesional']=perfil
        return context

def actualizarEstado(request):
    idUser = request.POST.get('idUsuario')
    estado = request.POST.get('estado')
    if request.method == 'POST':
     User.objects.filter(pk=idUser).update(
     is_active=estado,
     
     )
    return HttpResponseRedirect('/profesional/listarProfesional/')

templates/Profesional/ActualizarProfesional.html
{% extends 'Home/index.html' %}

{% block content %}

<div class="col-md-12">
    <form method="post" id="PacienteNuevo" enctype="multipart/form-data">
        
        {% csrf_token %} 
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Registro de Profesional</h5>
            </div>
            <div class="card-body">
                <input type="hidden" id="id_email" name="email" maxlength="150" value="{{ form2.email.initial }}">
                <input type="hidden" id="hfValidarFoto" name="validarFoto" value="NO">
                

                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Nombres: </label><span style=" color: red">*</span>
                        {{ form2.first_name }}
                        {{ form2.first_name.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">Apellidos: </label><span style=" color: red">*</span>
                        {{ form2.last_name }}
                        {{ form2.last_name.errors }}
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Cédula: </label><span style=" color: red">*</span>
                        {{ form.cedula }}
                        {{ form.cedula.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">Email: </label><span style=" color: red">*</span>
                        {{ form2.username }}
                        <!-- {{ form2.username.errors }} -->
                    </div>
                    

                </div>
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Contraseña: </label><span style=" color: red">*</span>
                        {{ form2.password }}
                        {{ form2.password.errors }}
                    </div>
                    
                    

                </div>
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Teléfono: </label><span style=" color: red">*</span>
                        {{ form.telefono }}
                        {{ form.telefono.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">Fecha de Nacimiento: </label><span style=" color: red">*</span>
                        {{ form.fecha_nacimiento }}
                        {{ form.fecha_nacimiento.errors }}
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Nacionalidad: </label><span style=" color: red">*</span>
                        {{ form.nacionalidad }}
                        {{ form.nacionalidad.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">Auto Identificación: </label><span style=" color: red">*</span>
                        {{ form.autoidentificacion }}
                        {{ form.autoidentificacion.errors }}
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Formación: </label><span style=" color: red">*</span>
                        {{ form.formacion }}
                        {{ form.formacion.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">Código MSP: </label><span style=" color: red">*</span>
                        {{ form.codigoMSP }}
                        {{ form.codigoMSP.errors }}
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Foto: </label><span style=" color: red">*</span>
                        {{ form.foto }}
                        {{ form.foto.errors }}
                    </div>
                    <div class="col-md-6">
                        <img src="{{profesional.foto}}" alt="" width="150px" class="rounded-circle">
                    </div>
                    
                </div>

                <div class="row form-group">
                    
                    
                </div>
                
            </div>
            <div class="card-footer text-center">
                <button class="btn btn-primary"   type="submit">
                    Guardar
                </button>
            </div>
        </div>


    </form>
</div>
{% for message in messages %}
    <div class="alert {{message.tags}}" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}

{% endblock %}

{% block scripts %}


<script type="text/javascript">
   
    $(document).ready(function() {
        setInterval(function(){

            if($('#id_foto').val() == ''){
                $('#hfValidarFoto').val('NO');
            }else{
                $('#hfValidarFoto').val('SI');
            }

            
        }, 100);
        $('.SoloLetras').keypress(function(e) {
            if(e.which < 97 /* a */ || e.which > 122 /* z */) {
                e.preventDefault();
            }
        });
        $('#id_cedula').on('input', function () { 
            this.value = this.value.replace(/[^0-9]/g,'');
        });
        $('#id_telefono').on('input', function () { 
            this.value = this.value.replace(/[^0-9]/g,'');
        });
        $('#id_username').keyup(function() {
            var email = this.value;
            $('#id_email').val(email);
        });

        //$('#id_foto').removeAttr("required");
     });
     
    
 </script>
 {% endblock %}

templates/Profesional/ListarProfesional.html
{% extends 'Home/index.html' %}
{% load static %}
{% block content %}
<style>
    .sweet-alert h2 {
        font-size: 1.2rem;
    }

    .sweet-alert .text-muted {
        font-size: 1.1rem;
    }

    .sa-button-container .cancel {
        font-size: 1rem;
    }

    .sa-confirm-button-container .confirm {
        font-size: 1rem;
    }
</style>
<link href="{% static 'assets/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
<div class="col-md-12" style="text-align: right;">
    <a href="{% url 'Profesional:registrarProfesional' %}" class="btn btn-primary"><i class="far fa-user"></i> Registrar
        Profesional</a>

</div>
<div class="col-md-12 mt-3">

    <div class="card">
        <div class="card-body">
            {% if profesional %}
            <table class="table table-bordered" id="tbProfesionales">
                <thead>
                    <tr>
                        <th style="display: none;">id</th>
                        <th style="background: #9ac10f; color: #fff;">Nombres</th>
                        <th style="background: #9ac10f; color: #fff;">Apellidos</th>
                        <th style="background: #9ac10f; color: #fff;">Cédula</th>

                        <th style="background: #9ac10f; color: #fff;">Teléfono</th>
                        <th style="background: #9ac10f; color: #fff;">Código MSP</th>
                        <th style="background: #9ac10f; color: #fff;">Editar</th>
                        <th style="background: #9ac10f; color: #fff;">Eliminar</th>
                    </tr>

                </thead>
                <tbody>
                    {% for i in profesional %}
                    <tr>
                        <td style="display: none;">{{i.id}}</td>
                        <td><a href="#">{{i.user.first_name}}</a></td>
                        <td>{{i.user.last_name}}</td>
                        <td>{{i.cedula}}</td>
                        <td>{{i.telefono}}</td>
                        <td>{{i.codigoMSP}}</td>

                        <td>
                            {% if i.user.is_active == True %}
                            <a href="{% url 'Profesional:actualizarProfesional' i.id  %}"
                                class="btn btn-primary">Editar</a>
                            {% else %}
                            <button type="button" class="btn btn-secondary">Editar</button>
                            {% endif %}
                        </td>
                        <td><button type="button" class="btn btn-success"
                                onclick="abrirmodalEstado('{{i.user.id}}','{{i.user.is_active}}')">Estado</a></td>
                    </tr>

                    {% endfor %}
                </tbody>
            </table>

            {% else %}
            <h4>No existen profesionales registrados</h4>
            {% endif %}
        </div>
    </div>
</div>


<div class="modal fade" id="modalCambioEstado" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Actualizar Estado</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <input type="hidden" id="hfIdUsuario">
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4">
                        <label for="">Estado:</label>
                    </div>
                    <div class="col-md-8">
                        <select id="ddlEstadoUser" class="form-control">
                            <option value="">---Seleccione---</option>
                            <option value="True">Activo</option>
                            <option value="False">Inactivo</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-success" onclick="validarCampos()">Actualizar</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'assets/js/jquery.dataTables4.min.js' %} "></script>
<script src="{% static 'assets/js/dataTables.bootstrap4.min.js' %} "></script>


<script type="text/javascript">

    $(document).ready(function () {

        $('#tbProfesionales').DataTable({
            order: [[ 0, "desc" ]],
            language: {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                },
                "buttons": {
                    "copy": "Copiar",
                    "colvis": "Visibilidad"
                }
            }
        });
    });

    function abrirmodalEstado(idUsuario, Estado) {

        $('#hfIdUsuario').val(idUsuario);
        $('#ddlEstadoUser').val(Estado);
        $('#modalCambioEstado').modal('show');
    }

    function validarCampos() {
        if ($('#ddlEstadoUser').val() == '') {
            alert('Seleccione un estado');
            retur;
        }

        actualizarEstado();
    }

    function actualizarEstado() {
        var idUsuario = $('#hfIdUsuario').val();
        var estado = $('#ddlEstadoUser').val();
        $.ajax({
            type: 'POST',
            url: '/profesional/actualizarestado/',
            data: {
                idUsuario: idUsuario,
                estado: estado,
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function (data) {
                location.reload();
                console.log("actualizado");

            },
            error: function (data) {
                console.log(data);
            }
        });

    }
</script>
{% endblock %}

templates/Profesional/RegistrarProfesional.html
{% extends 'Home/index.html' %}

{% block content %}

<div class="col-md-12">
    <form method="post" id="PacienteNuevo" enctype="multipart/form-data">
        
        {% csrf_token %} 
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Registro de Profesional</h5>
            </div>
            <div class="card-body">
                <input type="hidden" id="id_email" name="email" maxlength="150">
                
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Nombres: </label><span style=" color: red">*</span>
                        {{ form2.first_name }}
                        {{ form2.first_name.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">Apellidos: </label><span style=" color: red">*</span>
                        {{ form2.last_name }}
                        {{ form2.last_name.errors }}
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Cédula: </label><span style=" color: red">*</span>
                        {{ form.cedula }}
                        {{ form.cedula.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">Email: </label><span style=" color: red">*</span>
                        {{ form2.username }}
                        <!-- {{ form2.username.errors }} -->
                    </div>
                    

                </div>
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Contraseña: </label><span style=" color: red">*</span>
                        {{ form2.password }}
                        {{ form2.password.errors }}
                    </div>
                    
                </div>
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Teléfono: </label><span style=" color: red">*</span>
                        {{ form.telefono }}
                        {{ form.telefono.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">Fecha de Nacimiento: </label><span style=" color: red">*</span>
                        {{ form.fecha_nacimiento }}
                        {{ form.fecha_nacimiento.errors }}
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Nacionalidad: </label><span style=" color: red">*</span>
                        {{ form.nacionalidad }}
                        {{ form.nacionalidad.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">Auto Identificación: </label><span style=" color: red">*</span>
                        {{ form.autoidentificacion }}
                        {{ form.autoidentificacion.errors }}
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Formación: </label><span style=" color: red">*</span>
                        {{ form.formacion }}
                        {{ form.formacion.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">Código MSP: </label><span style=" color: red">*</span>
                        {{ form.codigoMSP }}
                        {{ form.codigoMSP.errors }}
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Foto: </label><span style=" color: red">*</span>
                        {{ form.foto }}
                        {{ form.foto.errors }}
                    </div>
                    
                </div>
                

                
            </div>
            <div class="card-footer text-center">
                <button class="btn btn-primary"   type="submit">
                    Guardar
                </button>
            </div>
        </div>


    </form>
</div>
{% for message in messages %}
    <div class="alert {{message.tags}}" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}

{% endblock %}

{% block scripts %}


<script type="text/javascript">
   
    $(document).ready(function() {
        
       
        $('.SoloLetras').keypress(function(e) {
            if((e.which < 97 /* a */ || e.which > 122) && e.which!=32  /* z */) {
                e.preventDefault();
            }
        }); 
        $('#id_cedula').on('input', function () { 
            this.value = this.value.replace(/[^0-9]/g,'');
        });
        $('#id_telefono').on('input', function () { 
            this.value = this.value.replace(/[^0-9]/g,'');
        });
        $('#id_username').keyup(function() {
            var email = this.value;
            $('#id_email').val(email);
        });
     });
     
    
 </script>
 {% endblock %}