SistemaTeleReabilitacion/urls.py
from django.conf.urls import url

from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/',LoginView.as_view(template_name='login.html'), name="login"),
    path('accounts/profile/',include('apps.inicio.urls', namespace="Inicio")),

    
    path(r'',include('apps.HomePrincipal.urls',namespace='indexHome')),

    path(r'',include('apps.inicio.urls', namespace="inicio")),
    
    path('logout/', LogoutView.as_view(), name="logout"),
    path('paciente/', include('apps.Paciente.urls'), name="Paciente"),
    path('profesional/', include('apps.Profesional.urls'), name="Profesional"),
    path('provincia/', include('apps.Provincia.urls'), name="Provincia")

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/HomePrincipal/urls.py
from django.conf.urls import url
from django.urls import path
from apps.HomePrincipal.views import index, paginaNosotros, paginaContacto,paginaServicios,paginaHorarios
app_name='indexHome'

urlpatterns=[
    path(r'',index,name="HomePrincipal"),
    path('Home/Nosotros/',paginaNosotros,name="HomeNosotros"),
    path('Home/Contacto/',paginaContacto,name="HomeContacto"),
    path('Home/Servicios/',paginaServicios,name="HomeServicios"),
    path('Home/Horarios/',paginaHorarios,name="HomeHorarios"),

    
]

apps/Paciente/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path
from apps.Paciente.views import listarPaciente,RegistrarPaciente,ActualizarPaciente,EliminarPaciente,VisualHistoriaClinica,listarSeguimientoPaciente,activarHC,eliminarPacineteV2,RegistrarRutina,listarControlPaciente,actualizarSesion,finalizarRutina,listarReportes,visualizarReporte,visualizarGraficas
app_name='Paciente'

urlpatterns=[
    path('listarPaciente/',login_required(listarPaciente.as_view()), name="listarPaciente"),
    path('registrarPaciente/',login_required(RegistrarPaciente.as_view()), name="registrarPaciente"),
    path('actualizarPaciente/<int:pk>/',login_required(ActualizarPaciente.as_view()), name="actualizarPaciente"),
    path('eliminarPaciente/<int:pk>/',login_required(EliminarPaciente.as_view()), name="eliminarPaciente"),
    path('visualizarHCPaciente/<int:pk>/',login_required(VisualHistoriaClinica.as_view()), name="visualizarHCPaciente"),
    path('listarSeguimiento/',login_required(listarSeguimientoPaciente.as_view()), name="listarSeguimiento"),
    path('activarHistoriaClinica/',activarHC, name="activarHistoriaClinica"),
    path('eliminarPacineteV2/',eliminarPacineteV2, name="eliminarPacineteV2"),
    

    path('registrarRutina/<int:pk>/',login_required(RegistrarRutina.as_view()), name="registrarRutina"),
    path('listarControl/<int:pk>/',login_required(listarControlPaciente.as_view()), name="listarControl"),
    path('actualizarSesion/',actualizarSesion, name="actualizarSesion"),
    path('finalizarRutina/',finalizarRutina, name="finalizarRutina"),



    path('listarReportes/',listarReportes.as_view(), name="listarReportes"),
    path('visualizarReporte/<int:pk>/',visualizarReporte.as_view(), name="visualizarReporte"),
    path('visualizarGraficas/<int:pk>/',visualizarGraficas.as_view(), name="visualizarGraficas"),
        
]

apps/Profesional/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from apps.Profesional.views import ActualizarProfesional,RegistrarProfesional,listarProfesional,actualizarEstado
app_name='Profesional'

urlpatterns=[
  
    path('registrarProfesional/',RegistrarProfesional.as_view(), name="registrarProfesional"),
    path('actualizarProfesional/<int:pk>/',ActualizarProfesional.as_view(), name="actualizarProfesional"),
    path('listarProfesional/',login_required(listarProfesional.as_view()), name="listarProfesional"),  
    path('actualizarestado/',actualizarEstado, name="actualizarestado"),     
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/Home/Contacto.html
{% extends 'Home/Home.html' %}
{% load static %}
{% block header %}
<style>
	@media (max-width: 768px) {
		#main {
			margin-top: 80px;
		}
	}

    .about .icofont-check-circled{
        border: 0px !important;
    }
    .lblDays{
        width: 100px;
        text-align: left;
    }
    .daysAtencion{
        width: 80%;
        margin: auto;
        text-align: center;
    }
    .section-title{
        padding-bottom: 0px;
    }
</style>
<header id="header" class="fixed-top ">
	<div class="container">

		<div class="logo float-left">
			<h1 class="text-light"><a href="{% url 'indexHome:HomePrincipal' %}"><span>FISIOATLAS</span></a></h1>
		</div>

		<nav class="nav-menu float-right d-none d-lg-block">
			<ul>
				<li><a href="{% url 'indexHome:HomePrincipal' %}">Home</a></li>
				<li ><a href="{% url 'indexHome:HomeNosotros' %}">Nosotros</a></li>
				<li><a href="{% url 'indexHome:HomeServicios' %}">Servicios</a></li>
				<li class="active"><a href="{% url 'indexHome:HomeContacto' %}">Contactos</a></li>
				<li>
					{% if user.id %}
					<a href="/accounts/profile/" class="btnSession">{{user.first_name|slice:"0:7"}}
						{{user.last_name|slice:"0:7"}}</a>
					{% else %}
					<a href="/accounts/profile/" class="btnSession">Iniciar Sesión</a>
					{% endif %}


				</li>
			</ul>
		</nav><!-- .nav-menu -->

	</div>
</header>

{% endblock %}
{% block contenerdor %}
<main id="main">

	<!-- ======= About Us Section ======= -->
	<section class="breadcrumbs">
		<div class="container">

			<div class="d-flex justify-content-between align-items-center">
				<h2>Contactos</h2>
				<ol>
					<li><a href="{% url 'indexHome:HomePrincipal' %}">Home</a></li>
					<li>Contactos</li>
				</ol>
			</div>

		</div>
	</section>

    <section class="contact" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
        <div class="container">
  
          <div class="row">
  
            <div class="col-lg-6">
  
              <div class="row">
                <div class="col-md-12">
                  <div class="info-box">
                    <i class="bx bx-map"></i>
                    <h3>Nuestra dirección</h3>
                    <p>Av. Miguel Iturralde, barrio Colaisa frente a la farmacia Comunitaria<br> Latacunga - Ecuador</p>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="info-box">
                    <i class="bx bx-envelope"></i>
                    <h3>Envianos un correo electrónico</h3>
                    <p>santy8516@gmail.com<br></p>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="info-box">
                    <i class="bx bx-phone-call"></i>
                    <h3>Llámanos</h3>
                    <p>+593 995337079<br>+593 987982214</p>
                  </div>
                </div>
              </div>
  
            </div>
  
            <div class="col-lg-6">
                <div class="row info-box" style="margin-bottom: 0px;">
                    <div class="col-md-12 text-center">
                        <div class="section-title">
                            <h2>Horarios de Atención</h2>
                          </div>
                    </div>
                    <div class="col-md-12  text-left">
                        <div class="about">
                            <div class="daysAtencion">
                                <ul>
                                    <li><i class="icofont-check-circled "></i><label class="lblDays">Lunes </label><label><strong>06:00 AM - 19:30 PM</strong></label></li>
                                    <li><i class="icofont-check-circled"></i><label class="lblDays">Martes </label><label><strong>06:00 AM - 19:30 PM</strong></label></li>
                                    <li><i class="icofont-check-circled"></i><label class="lblDays">Miércoles </label><label><strong>06:00 AM - 19:30 PM</strong></label></li>
                                    <li><i class="icofont-check-circled"></i><label class="lblDays">Jueves </label><label><strong>06:00 AM - 19:30 PM</strong></label></li>
                                    <li><i class="icofont-check-circled"></i><label class="lblDays">Viernes </label><label><strong>06:00 AM - 19:30 PM</strong></label></li>
                                    <li><i class="icofont-check-circled"></i><label class="lblDays">Sábado </label><label><strong>08:00 AM - 15:00 PM</strong></label></li>
                                    <li><i class="icofont-check-circled"></i><label class="lblDays">Domingo </label><label><strong>08:00 AM - 15:00 PM</strong></label></li>
                                    
                                  </ul>
                            </div>
                            
                        </div>
                        
                    </div>
                    
                </div>
               
            </div>
  
          </div>
  
        </div>
      </section><!-- End Contact Section -->
  
      <!-- ======= Map Section ======= -->
      <section class="map mt-2">
        <div class="container-fluid p-0">
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3989.3272736810086!2d-78.6204711857271!3d-0.8989321355786579!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x91d461b22072e4b9%3A0xdaf32f0451a20ede!2sCentro%20de%20Rehabilitaci%C3%B3n%20F%C3%ADsica%20y%20Deportiva%20FISIOATLAS!5e0!3m2!1ses-419!2sec!4v1607110265749!5m2!1ses-419!2sec" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
        </div>
      </section><!-- End Map Section -->
  




</main>
<!-- Hero section end -->

{% endblock %}

templates/Home/Nosotros.html
{% extends 'Home/Home.html' %}
{% load static %}
{% block header %}
<style>
	@media (max-width: 768px) {
		#main {
			margin-top: 80px;
		}
	}
</style>
<header id="header" class="fixed-top ">
	<div class="container">

		<div class="logo float-left">
			<h1 class="text-light"><a href="{% url 'indexHome:HomePrincipal' %}"><span>FISIOATLAS</span></a></h1>
		</div>

		<nav class="nav-menu float-right d-none d-lg-block">
			<ul>
				<li><a href="{% url 'indexHome:HomePrincipal' %}">Home</a></li>
				<li class="active"><a href="{% url 'indexHome:HomeNosotros' %}">Nosotros</a></li>
				<li><a href="{% url 'indexHome:HomeServicios' %}">Servicios</a></li>
				<li><a href="{% url 'indexHome:HomeContacto' %}">Contactos</a></li>
				<li>
					{% if user.id %}
					<a href="/accounts/profile/" class="btnSession">{{user.first_name|slice:"0:7"}}
						{{user.last_name|slice:"0:7"}}</a>
					{% else %}
					<a href="/accounts/profile/" class="btnSession">Iniciar Sesión</a>
					{% endif %}


				</li>
			</ul>
		</nav><!-- .nav-menu -->

	</div>
</header>

{% endblock %}
{% block contenerdor %}
<main id="main">

	<!-- ======= About Us Section ======= -->
	<section class="breadcrumbs">
		<div class="container">

			<div class="d-flex justify-content-between align-items-center">
				<h2>Nosotros</h2>
				<ol>
					<li><a href="{% url 'indexHome:HomePrincipal' %}">Home</a></li>
					<li>Nosotros</li>
				</ol>
			</div>

		</div>
	</section>

	<section class="services">
		<div class="container">

			<div class="row">


				<div class="col-md-6 col-lg-6 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="100">
					<div class="icon-box icon-box-cyan">
						<div class="icon"><i class="bx bx-pulse"></i></div>
						<h4 class="title"><a href="">Misión</a></h4>
						<p class="description">Ser un consultorio reconocido en la ciudad de Latacunga brindando una
							excelente atención y ayudando a aliviar dolores físicos de cada uno de los pacientes.</p>
					</div>
				</div>

				<div class="col-md-6 col-lg-6 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="200">
					<div class="icon-box icon-box-green">
						<div class="icon"><i class="bx bx-show-alt"></i></div>
						<h4 class="title"><a href="">Visión</a></h4>
						<p class="description">En 5 años consolidarse en una clínica que brinde atención a múltiples
							áreas médicas, teniendo como objetivo principal la rehabilitación física y deportiva.</p>
					</div>
				</div>



			</div>

		</div>
	</section>



	<section class="about" data-aos="fade-up">
		<div class="container">

			<div class="row">
				<div class="col-lg-6">
					<img src="{% static 'assets/Comercial/img/doctor_2.jpg' %}" class="img-fluid" alt="">
				</div>
				<div class="col-lg-6 pt-4 pt-lg-0">
					<h3>Centro de Fisioterapia</h3>
					<p class="text-justify">FISIOATLAS, es un consultorio de fisioterapia que nace por iniciativa de
						ayudar a las personas y deseos de crecimiento personal y profesional de su principal socio
						fundador, el Lic. Henry Santiago Chanatasig Meza, profesional en el área de la ciencia de la
						salud que ofrece un tratamiento terapéutico y de rehabilitación no farmacológica para
						diagnosticar, prevenir y tratar síntomas de múltiples dolencias, brindando altos estándares de
						seguridad, calidad y excelencia.
						<br>
						<br>
						Es así como en el año 2018 se genera el sueño de crear el Centro de Rehabilitación física y
						deportiva “FISIOATLAS”, el mismo que se constituye un 12 de febrero del 2019 en la ciudad de
						Latacunga en la Parroquia de San Buenaventura teniendo como perspectiva desde sus inicios como
						meta fundamental superar las exigencias de sus pacientes y las expectativas del resto de
						consultorios, estándares de calidad que le permitirán ser conocido a nivel nacional.
						<br>
						<br>
						Como información importante y relevante el nombre de Fisioatlas, proviene de los termino; FISIO
						– en honor a la profesión el ser Fisioterapeuta y ATLAS – al nombre de la primera vertebra del
						cuerpo y la más importante.
						<br>
						<br>

					</p>
				</div>
			</div>

			<div class="row mt-3">

				<div class="col-lg-6 pt-4 pt-lg-0">
					<p class="text-justify">
						Resumiendo, sus inicios nuestro preciado consultorio comenzó con su principal instrumento sus
						manos, que son hasta el día de hoy gran ayuda para el sin número de pacientes que aprecian y
						agradecen el trabajo realizado y han dado esperanzas y alivio a cada uno de ellos, un electro
						estimulador, un ultrasonido y un aceite Johnson que quedo de la finalización de su tesis,
						teniendo como primer paciente a su abuelito quien fue también parte de este sueño y con quien
						comenzó este gran trabajo.
						<br>
						<br>
						El consultorio continuo en proceso de crecimiento, desarrollo y aprendizaje cada día dedicándose
						a la rama de recuperación en cupping, pediatría, geriátrica, terapia deportiva, respiratoria,
						instrumental, traumatología, manual ortopédico, estimulación temprana y punción seca metamérica;
						siendo así un consultorio reconocido y recomendado por todos quienes llegan a él.
						<br>
						<br>
						Hasta el día de hoy este sueño se mantiene latente y crece cada día con el apoyo de las personas
						que buscan una ayuda a sus problemas de dolor encontrando en FisioAtlas su recuperación.

					</p>
				</div>
				<div class="col-lg-6">
					<img src="{% static 'assets/Comercial/img/centro2.jpg' %}" class="img-fluid" alt="">
				</div>
			</div>

		</div>
	</section>


	<section class="services section-bg">
		<div class="container">
			<div class="section-title">
				<h2>Profesional</h2>
			</div>

			<div class="row" style="justify-content: center;">
				<div class="col-md-6 col-lg-4 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="200">
					<div class="icon-box icon-box-blue">
						<img class="card-img-top border" src="{% static 'assets/img/fisio.jpg' %}" alt="Card image cap">
						<div class="icon my-3"><i class="bx bx-first-aid"></i></div>
						<h4 class="title"><a href="">Lic. Henrry Santiago Chanatasig Meza</a></h4>
						<p class="description">Fisioterapeuta</p>
						<p class="description">Experto en Rehabilitación Física y Deportiva</p>

					</div>
				</div>

			</div>

		</div>
	</section>





</main>
<!-- Hero section end -->

{% endblock %}

templates/Home/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Centro de Rehabilitación Física y Deportiva FISIOATLAS</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %} " rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'assets/css/sb-admin-2.min.css' %}" rel="stylesheet">
  {% block newCSS %}
    <style>
      .bg-gradient-primary{
        background-color: red;
        background-image:linear-gradient(180deg,#09accc 10%,#09accc 100%) ;
      }
      .sidebar .nav-item .nav-link span{
        font-size: 1.2 rem !important;
      }
      .btn-primary , .page-item.active .page-link {
          color: #fff !important;
          background-color: #09ACCB !important;
          border-color: #869a9e !important;
      }

    </style>
  {% endblock %}

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'indexHome:HomePrincipal' %}">
        
        <img src="{% static 'assets/img/logoFisioAtlas.png' %}" alt="" style="width: 70%; ">
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">
      <li class="nav-item">
        <a class="nav-link collapsed" href="/accounts/profile/">
          <i class="fas fa-house-user"></i>
          <span>Mi Perfil</span>
        </a>  
      </li>
      {% if  user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link collapsed" href="{% url 'Profesional:listarProfesional' %}">
            <i class="fas fa-users"></i>
            <span>Profesionales</span>
          </a>
        </li>
      {% endif %}
      

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'Paciente:listarPaciente' %}">
          <i class="fas fa-users"></i>
          <span>Pacientes</span>
        </a>
      </li>
      
      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'Paciente:listarSeguimiento' %}" >
          <i class="fas fa-fw fa-wrench"></i>
          <span>Seguimiento</span>
        </a>
        
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'Paciente:listarReportes' %}" >
          <i class="fas fa-list-alt"></i>
          <span>Reportes</span>
        </a>
      </li>

    </ul>

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            

            

            

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.first_name}} {{user.last_name}}</span>
                <img class="img-profile rounded-circle" style="object-fit: fill;" src="{{Profesional.foto}}">
              </a>

              
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'logout' %}">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Cerrar Sesión
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        {% block content %}

          
        <div class="container-fluid mt-2">

          <div class="row">
            <div class="col-xl-6 col-lg-6">
              <div class="card shadow" style="height:100%;">
                <div class="card-body" style="text-align: center;">
                  
                  
                  <img src="{{Profesional.foto}}" style="object-fit: fill;border-radius: 40px;margin-top: 2.5rem;" class="" alt="" width="300" height="300" ></br>
                  
                  
                  <h5 class="m-0 font-weight-bold text-primary mt-5">{{user.first_name}} {{user.last_name}}</h5>
                </div>
              </div>
            </div>
            <!-- Area Chart -->
            <div class="col-xl-6 col-lg-6">
              <div class="card shadow " style="height: 100%;">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Datos del profesional</h6>
                  
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  <!-- <div class="row" >
                    
                    <div class="col-md-12 text-right">
                      <a href="{% url 'Profesional:actualizarProfesional' user.id  %}">Editar perfil</a>
                    </div>
                    
                  </div> -->
                </br>
                  <div class="row form-group">
                    <div class="col-md-6">
                      <label for="" class="font-weight-bold">Cédula:&nbsp;</label></br>
                      <label for="">{{ Profesional.cedula }}</label>

                    </div>

                    <div class="col-md-6">
                      <label for="" class="font-weight-bold">Email:&nbsp;</label></br>
                      <label for="">{{ user.email }}</label>
                    </div>
                    
                  </div>

                  <div class="row form-group">
                    <div class="col-md-6">
                      <label for="" class="font-weight-bold">Teléfono:&nbsp;</label></br>
                      <label for="">{{ Profesional.telefono }}</label>
                    </div>

                    <div class="col-md-6">
                      <label for="" class="font-weight-bold">Fecha de Nacimiento:&nbsp;</label></br>
                      <label for="">{{ Profesional.fecha_nacimiento|date:"SHORT_DATE_FORMAT" }}</label>
                    </div>
                  </div>

                  <div class="row form-group">
                    <div class="col-md-6">
                      <label for="" class="font-weight-bold">Nacionalidad:&nbsp;</label></br>
                      <label for="">{{ Profesional.nacionalidad }}</label>
                    </div>

                    <div class="col-md-6">
                      <label for="" class="font-weight-bold">Auto Identificación:&nbsp;</label></br>
                      <label for="">{{ Profesional.autoidentificacion }}</label>
                    </div>
                  </div>

                  <div class="row form-group">
                    <div class="col-md-6">
                      <label for="" class="font-weight-bold">Formación:&nbsp;</label></br>
                      <label for="">{{ Profesional.formacion }}</label>
                    </div>

                    <div class="col-md-6">
                      <label for="" class="font-weight-bold">Código MSP:&nbsp;</label></br>
                      <label for="">{{ Profesional.codigoMSP }}</label>
                    </div>
                  </div>

                </div>
              </div>
            </div>

            
          </div>

          

        </div>
        {% endblock %}
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %} "></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'assets/vendor/jquery-easing/jquery.easing.min.js' %} "></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'assets/js/sb-admin-2.min.js' %} "></script>
  <script src="{% static 'assets/js/moment.min.js' %} "></script>
 

  <!-- Page level plugins -->
  <!-- <script src="{% static 'assets/vendor/chart.js/Chart.min.js' %} "></script> -->

  <!-- Page level custom scripts -->
  <!-- <script src="{% static 'assets/js/demo/chart-area-demo.js' %} "></script>
  <script src="{% static 'assets/js/demo/chart-pie-demo.js' %} "></script> -->
  {% block scripts %}
  {% endblock %}
</body>

</html>