SistemaTeleReabilitacion/urls.py
from django.conf.urls import url

from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/',LoginView.as_view(template_name='login.html'), name="login"),
    path('accounts/profile/',include('apps.inicio.urls', namespace="Inicio")),

    
    path(r'',include('apps.HomePrincipal.urls',namespace='indexHome')),

    path(r'',include('apps.inicio.urls', namespace="inicio")),
    
    path('logout/', LogoutView.as_view(), name="logout"),
    path('paciente/', include('apps.Paciente.urls'), name="Paciente"),
    path('profesional/', include('apps.Profesional.urls'), name="Profesional"),
    path('provincia/', include('apps.Provincia.urls'), name="Provincia")

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/Paciente/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path
from apps.Paciente.views import listarPaciente,RegistrarPaciente,ActualizarPaciente,EliminarPaciente,VisualHistoriaClinica,listarSeguimientoPaciente,activarHC,eliminarPacineteV2,RegistrarRutina,listarControlPaciente,actualizarSesion,finalizarRutina,listarReportes,visualizarReporte,visualizarGraficas
app_name='Paciente'

urlpatterns=[
    path('listarPaciente/',login_required(listarPaciente.as_view()), name="listarPaciente"),
    path('registrarPaciente/',login_required(RegistrarPaciente.as_view()), name="registrarPaciente"),
    path('actualizarPaciente/<int:pk>/',login_required(ActualizarPaciente.as_view()), name="actualizarPaciente"),
    path('eliminarPaciente/<int:pk>/',login_required(EliminarPaciente.as_view()), name="eliminarPaciente"),
    path('visualizarHCPaciente/<int:pk>/',login_required(VisualHistoriaClinica.as_view()), name="visualizarHCPaciente"),
    path('listarSeguimiento/',login_required(listarSeguimientoPaciente.as_view()), name="listarSeguimiento"),
    path('activarHistoriaClinica/',activarHC, name="activarHistoriaClinica"),
    path('eliminarPacineteV2/',eliminarPacineteV2, name="eliminarPacineteV2"),
    

    path('registrarRutina/<int:pk>/',login_required(RegistrarRutina.as_view()), name="registrarRutina"),
    path('listarControl/<int:pk>/',login_required(listarControlPaciente.as_view()), name="listarControl"),
    path('actualizarSesion/',actualizarSesion, name="actualizarSesion"),
    path('finalizarRutina/',finalizarRutina, name="finalizarRutina"),



    path('listarReportes/',listarReportes.as_view(), name="listarReportes"),
    path('visualizarReporte/<int:pk>/',visualizarReporte.as_view(), name="visualizarReporte"),
    path('visualizarGraficas/<int:pk>/',visualizarGraficas.as_view(), name="visualizarGraficas"),
        
]

apps/Rutina/models.py
from django.db import models

# Create your models here.

from apps.Juego.models import Juego
from apps.HistoriaClinica.models import HistoriaClinica

class Rutina(models.Model):
    
    fecha_inicio = models.DateField(blank=True, null=True)
    fecha_fin = models.DateField(blank=True, null=True)
    num_sesion = models.IntegerField(blank=True, null=True)
    preescripcion = models.CharField(max_length=300, blank=True, null=True)
    mano_derecha = models.BooleanField(blank=True, null=True)
    historiaClinica = models.ForeignKey(HistoriaClinica, on_delete=models.CASCADE, blank=True, null=True)
    estado= models.CharField(max_length=30,blank=True, null=True)

templates/Seguimiento/CrearRutina.html
{% extends 'Home/index.html' %}
{% load static %}
{% block content %}
<link href="{% static 'assets/css/sweetalert.css' %}" rel="stylesheet">
<script src="{% static 'assets/js/sweetalert.js' %} "></script>
<style>
    .card-header{
        background-color: #fff;
    }
    .tamanio{
        width: 180px !important;
    }
    #id_num_sesion{
        width: 100px !important;
    }
    #id_preescripcion{
        height: 90px ;
    }
</style>
<style>
    .sweet-alert h2{
        font-size: 1.2rem ;
    }
    .sweet-alert .text-muted{
        font-size: 1.1rem;
    }
    .sa-button-container .cancel{
        font-size: 1rem;
    }
    .sa-confirm-button-container .confirm {
        font-size: 1rem ;
    }
</style>
<style>
    .switch {
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }

    .switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }

    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #d46464;
        -webkit-transition: .4s;
        transition: .4s;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 26px;
        width: 26px;
        left: 4px;
        bottom: 4px;
        background-color: white;
        -webkit-transition: .4s;
        transition: .4s;
    }

    input:checked+.slider {
        background-color: #2196F3;
    }

    input:focus+.slider {
        box-shadow: 0 0 1px #2196F3;
    }

    input:checked+.slider:before {
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 34px;
    }

    .slider.round:before {
        border-radius: 50%;
    }
    .form-control[readonly]{
        background-color: #fff !important;
    }
</style>
<div class="col-md-12">
    <form method="post" id="PacienteNuevo" enctype="multipart/form-data">
        
        {% csrf_token %} 
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Registro Actividad paciente: {{paciente1.user.first_name}} {{paciente1.user.last_name}}</h5>
                
            </div>
            <div class="card-body">
                <input type="hidden" id="id_historiaClinica" name="historiaClinica" value="{{historiaC.id}}">
                <div class="row">
                    <div class="col-md-2"><label class="font-weight-bold">Fecha Inicio:</label></div>
                    <div class="col-md-3">
                        {{ form.fecha_inicio}}
                        {{ form.fecha_inicio.error }}
                    </div>
                    <div class="col-md-2"><label class="font-weight-bold">Fecha Fin:</label></div>
                    <div class="col-md-3">
                        {{ form.fecha_fin }}
                        {{ form.fecha_fin.error }}
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-2"><label class="font-weight-bold">Número sesiones:</label></div>
                    <div class="col-md-3">
                        {{ form.num_sesion }}
                        {{ form.num_sesion.error }}
                    </div>
                    <div class="col-md-2"><label class="font-weight-bold">Mano:</label></div>
                    <div class="col-md-3">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1" value="0" onclick="cambiarMano(this.value)" checked>
                            <label class="form-check-label" for="flexRadioDefault1">
                              Derecha
                            </label>
                          </div>
                          <div class="form-check">
                            <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" value="1" onclick="cambiarMano(this.value)" >
                            <label class="form-check-label" for="flexRadioDefault2">
                              Izquierda
                            </label>
                          </div>
                          <input type="hidden" id="id_mano_derecha" name="mano_derecha" value="0">
                    </div>
                </div>
                <div class="row mt-3">
                    
                    <div class="col-md-2"><label class="font-weight-bold">Observación:</label></div>
                    <div class="col-md-5">
                        {{ form.preescripcion }}
                        {{ form.preescripcion.error }}
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col">
                        <h5 class="card-title">Seleccione los juegos</h5>
                    </div>
                    
                </div>
                <div class="col-md-12 mt-3">
                    
                    <div class="row" style="justify-content: center;">
                        {% for i in Juegos %}
                        <div class="card col-md-3 m-4" style="width: 18rem;">

                            {% if i.id == 1 %}
                                <img class="card-img-top" src="{% static 'assets/img/salta.png' %}" alt="Card image cap">
                            {% elif i.id == 2 %}
                                <img class="card-img-top" src="{% static 'assets/img/nave.png' %}" alt="Card image cap">
                            {% elif i.id == 3 %}
                                <img class="card-img-top" src="{% static 'assets/img/laberinto.png' %}" alt="Card image cap">
                            {% endif %}

                            <div class="card-body" >
                            <diw class="row">
                                <div class="col-md-4">

                                    <label class="switch">
                                        <input type="checkbox"  class="verificarJuego" value="{{i.id}}">
                                        <span class="slider round"></span>
                                    </label>
                                    
                                </div>
                                <div class="col-md-6">
                                    <label for="" id="lblEstadoJuego_{{i.id}}"  class="mt-2 estadoJuegolbl">Inactivo</label>
                                </div>
                                <input type="hidden"  id="hfchkJuego_{{i.id}}" name="juegonNum{{i.id}}" value="NO" class="verificarSINO">
                                
                                <div class="col-md-6"  style="display: none;">
                                    <input  disabled type="number"  id="txtNumSesionesJuego_{{i.id}}" name="NumSesionesJuego{{i.id}}" class="form-control onlyNumbers numsesionesInd" value="0" >
                                    
                                </div>
                            </diw>
                            </div>

                            <div class="card-body" style="height: 70%;">
                              <h5 class="card-title"> {{i.nombre}}</h5>
                              <p class="card-text " style="text-align: justify;">  {{i.description}}</p>
                            </div>
                            
                            
                          </div>
                          {% endfor  %}
                    </div>
                    
                                             
                    
                </div>
            </div>
            <div class="card-footer text-center">
                <button class="btn btn-primary"   type="submit" id="btnGuardarRutina">
                    Guardar
                </button>
            </div>
        </div>


    </form>
</div>


{% for message in messages %}
    <div class="alert {{message.tags}}" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}

{% endblock %}

{% block scripts %}


<script type="text/javascript">
   var diasDisponibles=0;
    $(document).ready(function() {
        /* $('#id_num_sesion').attr('disabled',true) */
        document.getElementById("id_num_sesion").readOnly = true;
        var fecha=moment(new Date()).format("yyyy-MM-DD");
        $('.datepicker').val(fecha);


        $('#id_num_sesion').on('input', function () { 
            this.value = this.value.replace(/[^0-9]/g,'');
        });
        $('.onlyNumbers').on('input', function () { 
            this.value = this.value.replace(/[^0-9]/g,'');
        });

        $('#id_num_sesion').val(1)
     });
     
    function cambiarMano(valor){
        $('#id_mano_derecha').val(valor);
    }

    $('.verificarJuego').change(function(){
        
        if($(this).prop('checked')){
            $('#txtNumSesionesJuego_'+this.value).attr('disabled',false);
            $('#hfchkJuego_'+this.value).val('SI');
            $('#lblEstadoJuego_'+this.value).text('Activo');
        }else{
            $('#txtNumSesionesJuego_'+this.value).val(0);
            $('#txtNumSesionesJuego_'+this.value).attr('disabled',true);
            $('#hfchkJuego_'+this.value).val('NO');
            $('#lblEstadoJuego_'+this.value).text('Inactivo');
        }

        var numckh = $('.verificarJuego:checked').length ;
        var numSesiones=$('#id_num_sesion').val();

        var calculado= parseInt(numSesiones)/parseInt(numckh);
        if (calculado % 1 == 0) {
            llenarNumSesiones(calculado)
        } /* else {
            swal('El número de sesiones debe ser múltiplo al numero de juegos seleccionados');
            $('.numsesionesInd').val(0);
            $('.verificarSINO').val('NO');
            $('.verificarJuego').prop('checked',false);
            $('.estadoJuegolbl').text('Inactivo');
        } */


    });

    function llenarNumSesiones(num){

        $('.verificarJuego').each(function(){
            if($(this).prop('checked')){
               $('#txtNumSesionesJuego_'+this.value).val(num);
                
            }else{
                $('#txtNumSesionesJuego_'+this.value).val(0);
                
            }

        });

    }


    $('.datepicker').change(function(){
        $('.numsesionesInd').val(0);
        $('.verificarSINO').val('NO');
        $('.verificarJuego').prop('checked',false);
        $('.estadoJuegolbl').text('Inactivo');

        if($('#id_fecha_inicio').val()==''){
            swal('Ingrese la fecha Inicio');
            return;
        }
        if($('#id_fecha_fin').val()==''){
            swal('Ingrese la fecha Fin');
            return;
        }
        

        obtenerNumeroDias();
    });

    function obtenerNumeroDias(){
        var fechaInicio= $('#id_fecha_inicio').val();
        var fechaFin= $('#id_fecha_fin').val();

        var DateInicio=new Date(fechaInicio.replaceAll('/','-'));
        var DateFin=new Date(fechaFin.replaceAll('/','-'));
        
        if(DateInicio>DateFin){
            swal('La fecha Inicio no puede ser mayor a la fecha fin');
            var fecha=moment(new Date()).format("yyyy-MM-DD");
            $('.datepicker').val(fecha);
            return;
        }
        var fecha1 = moment(DateInicio);
        var fecha2 = moment(DateFin);

        var dias=fecha2.diff(fecha1, 'days');
        diasDisponibles=parseInt(dias)+1;
        $('#id_num_sesion').val(diasDisponibles);
       
    }

    
    $( "#btnGuardarRutina" ).click(function( event ) {
        var fechaInicio= $('#id_fecha_inicio').val()+'T23:59:00';
        var fechaFin= $('#id_fecha_fin').val()+'T23:59:00';

        var DateInicio=new Date(fechaInicio.replaceAll('/','-'));
        var DateFin=new Date(fechaFin.replaceAll('/','-'));
        var fechaActual = new Date();


        if(DateInicio<fechaActual){
            swal('La fecha Inicio no puede ser menor a la fecha actual');
            event.preventDefault();
            return;
        }


        if(DateInicio>DateFin){
            swal('La fecha Inicio no puede ser mayor a la fecha fin');
            event.preventDefault();
            return;
        }

        if($('#id_num_sesion').val()== '' || $('#id_num_sesion').val()== '0'){
            swal('El núnero de sesiones no puede ser 0 o vacio');
            event.preventDefault();
            return;
        }

        if($('.verificarJuego:checked').length == 0){
            swal('Debe activar almenos un juego');
            event.preventDefault();
            return;
        }
        var numckh = $('.verificarJuego:checked').length ;
        var numSesiones=$('#id_num_sesion').val();

        var calculado= parseInt(numSesiones)/parseInt(numckh);
        if (calculado % 1 == 0) {
            console.log('correcto')
        } else {
            swal('El número de sesiones debe ser múltiplo al número de juegos seleccionados');
            $('.numsesionesInd').val(0);
            $('.verificarSINO').val('NO');
            $('.verificarJuego').prop('checked',false);
            $('.estadoJuegolbl').text('Inactivo');
            event.preventDefault();
            return;
        }


        
        
    });
 </script>
 {% endblock %}

templates/Seguimiento/ListarSeguimiento.html
{% extends 'Home/index.html' %}
{% load static %}
{% block content %}
<style>
    .sweet-alert h2{
        font-size: 1.2rem ;
    }
    .sweet-alert .text-muted{
        font-size: 1.1rem;
    }
    .sa-button-container .cancel{
        font-size: 1rem;
    }
    .sa-confirm-button-container .confirm {
        font-size: 1rem ;
    }
</style>
<link href="{% static 'assets/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
<!-- <div class="col-md-12" style="text-align: right;">
    <a href="{% url 'Paciente:registrarPaciente' %}" class="btn btn-primary"><i class="far fa-user"></i> Registrar Paciente</a>

</div> -->
<div class="col-md-12 mt-3">

    <div class="card">
        <div class="card-body">
            {% if pacientes %}
                <table class="table table-bordered" id="tbSeguimiento">
                    <thead>
                        <tr >
                        <th style="display: none;">id</th>
                        <th style="background: #9ac10f; color: #fff;">Nombres</th>
                        <th style="background: #9ac10f; color: #fff;">Apellidos</th>
                        <th style="background: #9ac10f; color: #fff;">Cédula</th>
                        
                        <th style="background: #9ac10f; color: #fff;">Teléfono</th>
                        <th style="background: #9ac10f; color: #fff;">Fecha Cita</th>
                        <th style="background: #9ac10f; color: #fff;"></th>
                        
                        </tr>
                        
                    </thead>
                    <tbody>
                        {%  for i in pacientes %}
                        <tr>
                            <td style="display: none;">{{i.id}}</td>
                            <td><a href="#">{{i.user.first_name}}</a></td>
                            <td>{{i.user.last_name}}</td>
                            <td>{{i.cedula}}</td>
                            <td>{{i.telefono}}</td>
                            <td>{{i.fechaCita|date:'d-m-Y'}}</td>
                            
                            <td>
                                {% if i.seguimiento == 'SI' %}
                                    <a href="{% url 'Paciente:listarControl' i.id %}" class="btn btn-success">Control</a>
                                {% else %}
                                    <a href="{% url 'Paciente:registrarRutina' i.user.id  %}" class="btn btn-primary">Crear rutina</a>
                                {% endif %}    
                            </td>
                            
                        </tr>
                        
                        {% endfor %}
                    </tbody>   
                </table>
                
            {% else %}
                <h4>No existen pacientes con Rutinas Asignadas</h4>
            {% endif %}
        </div>
    </div>
</div>




    
{% endblock %}

{% block scripts %}
<script src="{% static 'assets/js/jquery.dataTables4.min.js' %} "></script>
<script src="{% static 'assets/js/dataTables.bootstrap4.min.js' %} "></script>


<script type="text/javascript">
   $(document).ready(function() {
        
        $('#tbSeguimiento').DataTable({
            order: [[0, "desc"]],
            language: {
                         "sProcessing": "Procesando...",
                         "sLengthMenu": "Mostrar _MENU_ registros",
                         "sZeroRecords": "No se encontraron resultados",
                         "sEmptyTable": "Ningún dato disponible en esta tabla",
                         "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                         "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                         "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                         "sInfoPostFix": "",
                         "sSearch": "Buscar:",
                         "sUrl": "",
                         "sInfoThousands": ",",
                         "sLoadingRecords": "Cargando...",
                         "oPaginate": {
                             "sFirst": "Primero",
                             "sLast": "Último",
                             "sNext": "Siguiente",
                             "sPrevious": "Anterior"
                         },
                         "oAria": {
                             "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                             "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                         },
                         "buttons": {
                             "copy": "Copiar",
                             "colvis": "Visibilidad"
                         }
                     }
        });
     });

 </script>
 {% endblock %}