SistemaTeleReabilitacion/urls.py
from django.conf.urls import url

from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/',LoginView.as_view(template_name='login.html'), name="login"),
    path('accounts/profile/',include('apps.inicio.urls', namespace="Inicio")),

    
    path(r'',include('apps.HomePrincipal.urls',namespace='indexHome')),

    path(r'',include('apps.inicio.urls', namespace="inicio")),
    
    path('logout/', LogoutView.as_view(), name="logout"),
    path('paciente/', include('apps.Paciente.urls'), name="Paciente"),
    path('profesional/', include('apps.Profesional.urls'), name="Profesional"),
    path('provincia/', include('apps.Provincia.urls'), name="Provincia")

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/Paciente/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path
from apps.Paciente.views import listarPaciente,RegistrarPaciente,ActualizarPaciente,EliminarPaciente,VisualHistoriaClinica,listarSeguimientoPaciente,activarHC,eliminarPacineteV2,RegistrarRutina,listarControlPaciente,actualizarSesion,finalizarRutina,listarReportes,visualizarReporte,visualizarGraficas
app_name='Paciente'

urlpatterns=[
    path('listarPaciente/',login_required(listarPaciente.as_view()), name="listarPaciente"),
    path('registrarPaciente/',login_required(RegistrarPaciente.as_view()), name="registrarPaciente"),
    path('actualizarPaciente/<int:pk>/',login_required(ActualizarPaciente.as_view()), name="actualizarPaciente"),
    path('eliminarPaciente/<int:pk>/',login_required(EliminarPaciente.as_view()), name="eliminarPaciente"),
    path('visualizarHCPaciente/<int:pk>/',login_required(VisualHistoriaClinica.as_view()), name="visualizarHCPaciente"),
    path('listarSeguimiento/',login_required(listarSeguimientoPaciente.as_view()), name="listarSeguimiento"),
    path('activarHistoriaClinica/',activarHC, name="activarHistoriaClinica"),
    path('eliminarPacineteV2/',eliminarPacineteV2, name="eliminarPacineteV2"),
    

    path('registrarRutina/<int:pk>/',login_required(RegistrarRutina.as_view()), name="registrarRutina"),
    path('listarControl/<int:pk>/',login_required(listarControlPaciente.as_view()), name="listarControl"),
    path('actualizarSesion/',actualizarSesion, name="actualizarSesion"),
    path('finalizarRutina/',finalizarRutina, name="finalizarRutina"),



    path('listarReportes/',listarReportes.as_view(), name="listarReportes"),
    path('visualizarReporte/<int:pk>/',visualizarReporte.as_view(), name="visualizarReporte"),
    path('visualizarGraficas/<int:pk>/',visualizarGraficas.as_view(), name="visualizarGraficas"),
        
]

apps/Paciente/models.py
from django.db import models
from apps.Provincia.models import Provincia
from apps.Canton.models import Canton
from apps.Profesional.models import Profesional
# Create your models here.
from django.contrib.auth.models import User

class Paciente(models.Model):
    vDependiente=( 
        ('SI','SI'),
        ('NO','NO')
    )
    cedula = models.CharField(max_length=20, blank=True, null=True)
    telefono = models.CharField(max_length=100, blank=True, null=True)
    fechaCita= models.DateField(blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    historiaClinica= models.CharField(max_length=100,choices=vDependiente,blank=True, null=True)
    seguimiento= models.CharField(max_length=100,choices=vDependiente,blank=True, null=True)
    patologia= models.CharField(max_length=300,blank=True, null=True)
    profesional=models.ForeignKey(Profesional, on_delete=models.CASCADE, blank=True, null=True)

apps/Paciente/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.models import User

from django.views.generic import CreateView,ListView,DeleteView,UpdateView,DetailView

from django.contrib import messages
from apps.Paciente.models import Paciente
from apps.Profesional.models import Profesional
from django.contrib.auth.hashers import make_password

from apps.Paciente.form import Pacienteform, Userform
from apps.HistoriaClinica.form import HistoriaClinicaform
from apps.Provincia.models import Provincia
from apps.HistoriaClinica.models import HistoriaClinica
from apps.Rutina.models import Rutina
from apps.Juego.models import Juego
from apps.RutinaJuego.models import RutinaJuego
from apps.Control.models import Control
from apps.Rutina.form import Rutinaform


from apps.Progreso.models import Progreso
from apps.Intento.models import Intento

from django.core import serializers
from django.core.mail import EmailMultiAlternatives
from django.db.models import Q

# Create your views here.


class listarPaciente(ListView):
    model = Paciente
    template_name='Paciente/ListarPaciente.html'
    def get_context_data(self, **kwargs):
        pk = self.request.user.id
        perfil = Profesional.objects.get(user_id=pk)
        profesionalId=Profesional.objects.filter(user_id=self.request.user.id).first()
        context = super().get_context_data(**kwargs)
        context['pacientes']=Paciente.objects.all().filter(profesional_id=profesionalId.id)
        context['Profesional']=perfil
        return context

class RegistrarPaciente(CreateView):
        model = Paciente
        template_name = "Paciente/RegistrarPaciente.html"
        form_class = Pacienteform
        second_form_class = Userform
        success_url = reverse_lazy('Paciente:listarPaciente')
        def get_context_data(self, **kwargs):
            
            pk = self.request.user.id
            perfil = Profesional.objects.get(user_id=pk)
            context= super(RegistrarPaciente,self).get_context_data(**kwargs)
            if 'form' not in context:
                context['form']= self.form_class(self.request.GET)
            if 'form2' not in context:
                context['form2']= self.second_form_class(self.request.GET)
            context['Profesional']=perfil
            return context
        def post(self, request, *args, **kwargs):
            self.object= self.get_object
            form= self.form_class(request.POST)#empleado
            form2 = self.second_form_class(request.POST)#usuario
            profesionalId=Profesional.objects.filter(user_id=self.request.user.id).first()
            if form.is_valid() and form2.is_valid():
                paciente = form.save(commit=False)
                paciente.user = form2.save()
                paciente.profesional_id= profesionalId.id
                paciente.save()
                return HttpResponseRedirect(self.get_success_url())
            else:
                messages.error(request,('Por favor registrese nuevamente..!!'))
                return self.render_to_response(self.get_context_data(form=form, form2=form2))
    

class ActualizarPaciente(UpdateView):
    model=Paciente
    second_model=User
    template_name = "Paciente/ActualizarPaciente.html"
    form_class =Pacienteform 
    second_form_class = Userform
    success_url = reverse_lazy('Paciente:listarPaciente')
    def get_context_data(self, **kwargs):
        pku = self.request.user.id
        perfil = Profesional.objects.get(user_id=pku)
        context = super().get_context_data(**kwargs) 
        pk = self.kwargs.get('pk',0)
        empleadoid=self.model.objects.get(id=pk)
        user=self.second_model.objects.get(id=empleadoid.user_id)
        if 'form' not in context:
            context['form']= self.form_class()
        if 'form2' not in context:
            context['form2']= self.second_form_class(instance=user)
        context['id']=pk
        context['Profesional']=perfil
        return context
    def post(self, request, *args, **kwargs):
        self.object= self.get_object
        id_empleado=self.kwargs.get('pk',0)
        empleadoid= self.model.objects.get(id=id_empleado)
        user=self.second_model.objects.get(id=empleadoid.user_id)
        form = self.form_class(request.POST, instance=empleadoid)
        form2= self.second_form_class(request.POST, instance=user) 
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            messages.error(request,('Por favor intente nuevamente'))
            return self.render_to_response(self.get_context_data(form=form, form2=form2))

class EliminarPaciente(DeleteView):
    model=Paciente
    template_name ='Paciente/EliminarPaciente.html'
    success_url = reverse_lazy('Paciente:listarPaciente')

class VisualHistoriaClinica(UpdateView):
    model=Paciente
    second_model=User
    third_model=HistoriaClinica
    template_name = "HistoriaClinica/ActualizarHistoriaClinica.html"
    form_class =Pacienteform 
    second_form_class = Userform
    third_form_class=HistoriaClinicaform
    success_url = reverse_lazy('Paciente:listarPaciente')
    def get_context_data(self, **kwargs): 
        pku = self.request.user.id
        perfil = Profesional.objects.get(user_id=pku)
        context = super().get_context_data(**kwargs) 
        pk = self.kwargs.get('pk',0)
        empleadoid=self.model.objects.get(id=pk)
        user=self.second_model.objects.get(id=empleadoid.user_id)
        historiaClinica=self.third_model.objects.get(paciente_id=empleadoid.id)
        if 'form' not in context:
            context['form']= self.form_class()
        if 'form2' not in context:
            context['form2']= self.second_form_class(instance=user)
        if 'form3' not in context:
                context['form3']= self.third_form_class(instance=historiaClinica)
        context['id']=empleadoid.id
        context['provincias'] = Provincia.objects.all().order_by('nombre')
        context['profesional']=Profesional.objects.get(user=self.request.user.id)
        context['Profesional']=perfil
        
        return context
    def post(self, request, *args, **kwargs):
        self.object= self.get_object
        id_empleado=self.kwargs.get('pk',0)
        empleadoid= self.model.objects.get(id=id_empleado)
        user=self.second_model.objects.get(id=empleadoid.user_id)
        historiaClinica=self.third_model.objects.get(paciente_id=empleadoid.id)
        form = self.form_class(request.POST, instance=empleadoid)
        form2= self.second_form_class(request.POST, request.FILES,instance=user) 
        form3 = self.third_form_class(request.POST, request.FILES,instance=historiaClinica)
        if form.is_valid() and form2.is_valid() and form3.is_valid():
            form.save()
            form2.save()
            form3.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            messages.error(request,('Por favor intente nuevamente'))
            return self.render_to_response(self.get_context_data(form=form, form2=form2))

class listarSeguimientoPaciente(ListView):
    model = Paciente
    template_name='Seguimiento/ListarSeguimiento.html'
    def get_context_data(self, **kwargs):
        pk = self.request.user.id
        perfil = Profesional.objects.get(user_id=pk)
        profesionalId=Profesional.objects.filter(user_id=self.request.user.id).first()
        context = super().get_context_data(**kwargs)
        context['pacientes']=Paciente.objects.all().filter(historiaClinica = 'SI',profesional_id=profesionalId.id) 
        context['Profesional']=perfil
        
        return context

def activarHC(request):
    idPaciente= request.POST.get('idPaciente')
   
    if request.method == 'POST':
        Paciente.objects.filter(pk=idPaciente).update(
            historiaClinica='SI'
        )

    hc=HistoriaClinica.objects.filter(paciente_id=idPaciente)
    
    if hc :
        print('existe')
    else:
        historiaC= HistoriaClinica.objects.create(paciente_id=idPaciente)
        historiaC.save()
    
    return HttpResponseRedirect('/paciente/listarPaciente/')


def eliminarPacineteV2(request):
    idPaciente= request.POST.get('idPaciente')
    if request.method == 'POST':
        pacienteInfo=Paciente.objects.get(pk=idPaciente)
        if pacienteInfo.user_id:
            User.objects.filter(pk=pacienteInfo.user_id).delete()
            pacienteInfo.delete()
    return HttpResponseRedirect('/paciente/listarPaciente/')


class RegistrarRutina(CreateView):
        model = Rutina
        template_name = "Seguimiento/CrearRutina.html"
        form_class = Rutinaform
        success_url = reverse_lazy('Paciente:listarSeguimiento')
        def get_context_data(self, **kwargs):
            
            context= super(RegistrarRutina,self).get_context_data(**kwargs)
            pku = self.request.user.id
            perfil = Profesional.objects.get(user_id=pku)
            idPacinete = self.kwargs.get('pk',0)
            idPHC=Paciente.objects.filter(user_id=idPacinete).first()
            
            if 'form' not in context:
                context['form']= self.form_class(self.request.GET)
            context['paciente1']=Paciente.objects.filter(user_id=idPacinete).first()
            context['historiaC']=HistoriaClinica.objects.filter(paciente_id=idPHC.id).first()
            context['Juegos']=Juego.objects.all()
            context['Profesional']=perfil
            
            return context
        def post(self, request, *args, **kwargs):
            self.object= self.get_object
            form= self.form_class(request.POST)#empleado
            
            if form.is_valid() :
                vRutina = form.save()
                vRutina.save()
                idRutina=vRutina.id
               

templates/Paciente/ActualizarPaciente.html
{% extends 'Home/index.html' %}

{% block content %}

<div class="col-md-12">
    <form method="post" id="PacienteNuevo" >
        
        {% csrf_token %} 
        <div class="card">
            <div class="card-body">
                <div class="row form-group">
                    <input type="hidden"  name="password" value="NA">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Cédula: </label><span style=" color: red">*</span>
                        {{ form.cedula }}
                        {{ form.cedula.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">User Name: </label><span style=" color: red">*</span>
                        {{ form2.username }}
                        {{ form2.username.errors }}
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Nombres: </label><span style=" color: red">*</span>
                        {{ form2.first_name }}
                        {{ form2.first_name.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">Apellidos: </label><span style=" color: red">*</span>
                        {{ form2.last_name }}
                        {{ form2.last_name.errors }}
                    </div>
                    
                </div>
                
                
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Teléfono: </label><span style=" color: red">*</span>
                        {{ form.telefono }}
                        {{ form.telefono.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">Fecha Cita: </label><span style=" color: red">*</span>
                        {{ form.fechaCita }}
                        {{ form.fechaCita.errors }}
                    </div>
                    
                </div>
                
                
            </div>
            <div class="card-footer text-center">
                <button class="btn btn-primary"   type="submit">
                    Guardar
                </button>
            </div>
        </div>


    </form>
</div>
<script type="text/javascript">
   
   $(document).ready(function() {
        $('#id_cedula').on('input', function () { 
            this.value = this.value.replace(/[^0-9]/g,'');
        });
    });
    
   
</script>
{% endblock %}

templates/Paciente/EliminarPaciente.html
{% extends 'Home/index.html' %}

{% block content %}

<div class="col-md-12">
    <form method="post" id="PacienteNuevo" >
        
        {% csrf_token %} 
        <div class="card">
            <div class="card-body">
                <div class="row form-group">
                    <div class="col-md-12">
                        <h4>¿Está seguro que desea eliminar el registro de <b>{{object.user.first_name}}  {{object.user.last_name}}</b>?
                
                    </div>
                    <div class="col-md-12">
                        <button class="btn btn-danger"   type="submit">
                            Sí, Eliminar
                        </button>
                        <a href="{% url 'Paciente:listarPaciente' %}" class="btn btn-primary">Cancelar</a>

                    </div>
                </div>
               
                
            </div>
            
        </div>


    </form>
</div>
<script type="text/javascript">
   
   $(document).ready(function() {
        $('#id_cedula').on('input', function () { 
            this.value = this.value.replace(/[^0-9]/g,'');
        });
    });
    
   
</script>
{% endblock %}

templates/Paciente/ListarPaciente.html
{% extends 'Home/index.html' %}
{% load static %}
{% block content %}
<link href="{% static 'assets/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
<link href="{% static 'assets/css/sweetalert.css' %}" rel="stylesheet">
<script src="{% static 'assets/js/sweetalert.js' %} "></script>
<style>
    .switch {
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }

    .switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }

    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 26px;
        width: 26px;
        left: 4px;
        bottom: 4px;
        background-color: white;
        -webkit-transition: .4s;
        transition: .4s;
    }

    input:checked+.slider {
        background-color: #2196F3;
    }

    input:focus+.slider {
        box-shadow: 0 0 1px #2196F3;
    }

    input:checked+.slider:before {
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 34px;
    }

    .slider.round:before {
        border-radius: 50%;
    }
</style>


<style>
    .sweet-alert h2 {
        font-size: 1.2rem;
    }

    .sweet-alert .text-muted {
        font-size: 1.1rem;
    }

    .sa-button-container .cancel {
        font-size: 1rem;
    }

    .sa-confirm-button-container .confirm {
        font-size: 1rem;
    }
</style>
<div class="col-md-12" style="text-align: right;">
    <a href="{% url 'Paciente:registrarPaciente' %}" class="btn btn-primary"><i class="far fa-user"></i> Registrar
        Paciente</a>

</div>
<div class="col-md-12 mt-3">

    <div class="card">
        <div class="card-body">
            {% if pacientes %}
            <table class="table table-bordered" id="tbListaPacientes">
                <thead>
                    <tr>
                        <th style="display: none;">id</th>
                        <th style="background: #9ac10f; color: #fff;">Nombres</th>
                        <th style="background: #9ac10f; color: #fff;">Apellidos</th>
                        <th style="background: #9ac10f; color: #fff;">Cédula</th>

                        <th style="background: #9ac10f; color: #fff;">Teléfono</th>
                        <th style="background: #9ac10f; color: #fff;">Fecha Cita</th>
                        <th style="background: #9ac10f; color: #fff;">Estado</th>
                        <th style="background: #9ac10f; color: #fff;">Acción</th>
                    </tr>

                </thead>
                <tbody>
                    {% for i in pacientes %}
                    <tr>
                        <td style="display: none;">{{i.id}}</td>
                        <td><a href="#">{{i.user.first_name}}</a></td>
                        <td>{{i.user.last_name}}</td>
                        <td>{{i.cedula}}</td>
                        <td>{{i.telefono}}</td>
                        <td>{{i.fechaCita|date:'d-m-Y'}} </td>
                        {% if i.historiaClinica == 'SI' %}
                        <td>
                            <label class="switch">
                                <input type="checkbox" class="verificarChekeados" id="chkidInput" disabled checked>
                                <span class="slider round"></span>
                            </label>
                        </td>
                        <td><a href="{% url 'Paciente:visualizarHCPaciente' i.id  %}" class="btn btn-primary">Historia
                                Clínica</a></td>
                        
                        {% else %}
                        <td>
                            <label class="switch">
                                <input type="checkbox" class="verificarChekeados" id="chkidInput_{{i.id}}"
                                    onchange="activarHistoriaClinica('{{i.id}}')">
                                <span class="slider round"></span>
                            </label>
                        </td>
                        
                        <td><button type="button" class="btn btn-danger"
                                onclick="confirmarEliminacion('{{i.id}}')">Eliminar</button></td>
                        {% endif %}
                    </tr>

                    {% endfor %}
                </tbody>
            </table>

            {% else %}
            <h4>No existen pacientes registrados</h4>
            {% endif %}
        </div>
    </div>
</div>


<script>

    function activarHistoriaClinica(idPaciente) {

        swal({
            title: "¿Esta seguro que desea activar la historia clinica?",
            //text: "Se eliminara el archivo",
            type: "warning",
            showCancelButton: true,
            confirmButtonClass: 'btn-info',
            cancelButtonClass: 'btn-danger',
            confirmButtonText: 'Si, continuar',
            cancelButtonText: 'Cancelar',
            closeOnConfirm: false,
            //closeOnCancel: false
        },
            function (confirmar) {
                if (confirmar) {

                    activarHC(idPaciente);
                } else {
                    $("#chkidInput_" + idPaciente).prop('checked', false);
                }


            });

    }

    function activarHC(idPaciente) {
        $.ajax({
            type: 'POST',
            url: '/paciente/activarHistoriaClinica/',
            data: {
                idPaciente: idPaciente,

                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function (data) {
                location.reload();


            },
            error: function (data) {
                console.log(data);
            }
        });
    }


    function confirmarEliminacion(idPaciente) {
        swal({
            title: "Esta seguro?",
            text: "Se eliminara el archivo",
            type: "warning",
            showCancelButton: true,
            confirmButtonClass: 'btn-info',
            cancelButtonClass: 'btn-danger',
            confirmButtonText: 'Si, eliminar',
            cancelButtonText: 'Cancelar',
            closeOnConfirm: false,
            //closeOnCancel: false
        },
            function () {
                eliminarPaciente(idPaciente);

            });
    }

    function eliminarPaciente(idPaciente) {
        $.ajax({
            type: 'POST',
            url: '/paciente/eliminarPacineteV2/',
            data: {
                idPaciente: idPaciente,

                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function (data) {
                location.reload();


            },
            error: function (data) {
                console.log(data);
            }
        });
    }
</script>


{% endblock %}

{% block scripts %}
<script src="{% static 'assets/js/jquery.dataTables4.min.js' %} "></script>
<script src="{% static 'assets/js/dataTables.bootstrap4.min.js' %} "></script>


<script type="text/javascript">
    $(document).ready(function () {

        $('#tbListaPacientes').DataTable({
            order: [[0, "desc"]],
            language: {
                
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                },
                "buttons": {
                    "copy": "Copiar",
                    "colvis": "Visibilidad"
                }
            }
        });
    });

</script>
{% endblock %}

templates/Paciente/RegistrarPaciente.html
{% extends 'Home/index.html' %}

{% block content %}

<div class="col-md-12">
    <form method="post"  enctype="multipart/form-data">
        
        {% csrf_token %} 
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Registro de Paciente</h5>
            </div>
            <div class="card-body">
                <input type="hidden"  name="password" value="NA">
                <input type="hidden" id="id_email" name="email" maxlength="150">
                <input type="hidden" id="id_historiaClinica" name="historiaClinica" value="NO">
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Nombres: </label><span style=" color: red">*</span>
                        {{ form2.first_name }}
                        {{ form2.first_name.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">Apellidos: </label><span style=" color: red">*</span>
                        {{ form2.last_name }}
                        {{ form2.last_name.errors }}
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Cédula: </label><span style=" color: red">*</span>
                        {{ form.cedula }}
                        {{ form.cedula.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">Email: </label><span style=" color: red">*</span>
                        {{ form2.username }}
                        <!-- {{ form2.username.errors }} -->
                    </div>
                    

                </div>
               
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Teléfono: </label><span style=" color: red">*</span>
                        {{ form.telefono }}
                        {{ form.telefono.errors }}
                    </div>
                    <div class="col-md-6">
                        <label class="font-weight-bold">Fecha Cita: </label><span style=" color: red">*</span>
                        {{ form.fechaCita }}
                        {{ form.fechaCita.errors }}
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-6">
                        <label class="font-weight-bold">Patología Aparente: </label><span style=" color: red">*</span>
                        {{ form.patologia }}
                        {{ form.patologia.errors }}
                    </div>
                    
                </div>
            
            </div>
            <div class="card-footer text-center">
                <button class="btn btn-primary"   type="submit">
                    Guardar
                </button>
            </div>
        </div>


    </form>
</div>
{% for message in messages %}
    <div class="alert {{message.tags}}" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {{ message }}
{% endfor %}

{% endblock %}

{% block scripts %}


<script type="text/javascript">
   
    $(document).ready(function() {
        
        /* $('.SoloLetras').keypress(function(e) {
            if(e.which < 97  || e.which > 122  || e.which == 32) {
                e.preventDefault();
            }
        }); */
        $('.SoloLetras').keypress(function(e) {
            if((e.which < 97 /* a */ || e.which > 122) && e.which!=32  /* z */) {
                e.preventDefault();
            }
        });
        $('#id_cedula').on('input', function () { 
            this.value = this.value.replace(/[^0-9]/g,'');
        });
        $('#id_telefono').on('input', function () { 
            this.value = this.value.replace(/[^0-9]/g,'');
        });
        $('#id_username').keyup(function() {
            var email = this.value;
            $('#id_email').val(email);
        });
     });
     
    
 </script>
 {% endblock %}